#!/usr/bin/env sh

# =============================================================================
# File:        .yabairc
# Maintainer:  Alex Sun (ranmaru22)
# GitHub:      https://github.com/ranmaru22/dotfiles
# =============================================================================

# Global Settings
# Mouse {{{
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
# }}}

# Windows {{{
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
# }}}

# Opacity {{{
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
# }}}

# Borders {{{
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xaad75f5f
# }}}

# Spaces {{{
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   10
yabai -m config external_bar                 all:35:0
# }}}

# Exceptions {{{
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off
# }}}

# Script helpers {{{
find "${TMPDIR}" -type f -perm +111 -name "yabai_${USER}_monocle_mode_*" -delete
# }}}

# Signals {{{
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"marsbar-index-jsx\"'"
yabai -m signal --add event=display_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"marsbar-index-jsx\"'"
yabai -m signal --add event=application_front_switched \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"marsbar-index-jsx\"'"
# }}}

# vim:foldmethod=marker:foldlevel=0
